apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  template:
    spec:
      containers:
        - name: workflow-controller
          image: 10.0.8.8:8088/kubeflow/2377459bc342c4555d11e2f0c375f592:2022-10-07
          args:
            - --configmap
            - workflow-controller-configmap
            - --executor-image
            - gcr.io/ml-pipeline/argoexec:v3.1.6-patch-license-compliance
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
