apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  template:
    spec:
      containers:
        - name: workflow-controller
          image: 10.0.8.8:8088/kubeflow/ml-pipeline-workflow-controller:v3.2.3
          args:
            - --configmap
            - workflow-controller-configmap
            - --executor-image
            - gcr.io/ml-pipeline/argoexec:v3.2.3-license-compliance
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
