apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  template:
    spec:
      containers:
        - name: workflow-controller
          image: 10.0.8.8:8088/kubeflow/dd2bda433848ef08a510a05f623d70d3:2022-10-07
          args:
            - --configmap
            - workflow-controller-configmap
            - --executor-image
            - gcr.io/ml-pipeline/argoexec:v3.3.8-license-compliance
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
