apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      serviceAccountName: kubeflow-pipelines-minio-gcs-gateway
      containers:
        - name: minio
          image: 10.0.8.8:8088/kubeflow/ml-pipeline-minio:dummy
          args:
            - gateway
            - gcs
            - $(GCP_PROJECT_ID)
          env:            
            - name: GCP_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: pipeline-install-config
                  key: gcsProjectId
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlpipeline-minio-artifact
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mlpipeline-minio-artifact
                  key: secretkey
          resources:
            requests:
              cpu: 20m
              memory: 25Mi
          ports:
            - containerPort: 9000
