apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  creationTimestamp: null
  name: mirror-image
spec:
  inputs:
    params:
      - name: inputImage
        type: string
      - name: outputImage
        type: string
      - name: context
        type: string
  steps:
    - image: 10.0.8.8:8088/kubeflow/ad9f7c3ae3310c11691d3ce7a9d5cefe:2022-10-07
      command:
      - /kaniko/executor
      - --dockerfile=Dockerfile
      - --context=$(inputs.params.context)
      - --destination=$(inputs.params.outputImage)
      - --build-arg INPUT_IMAGE=$(inputs.params.inputImage)
      name: build-push
