apiVersion: batch/v1
kind: Job
metadata:
  generateName: storage-version-migration-serving-
  namespace: knative-serving
  labels:
    app: storage-version-migration-serving
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: storage-version-migration-job
    app.kubernetes.io/version: "1.2.5"
    serving.knative.dev/release: "v1.2.5"
  name: storage-version-migration-serving
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 10
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: storage-version-migration-serving
        app.kubernetes.io/name: knative-serving
        app.kubernetes.io/component: storage-version-migration-job
        app.kubernetes.io/version: "1.2.5"
    spec:
      serviceAccountName: controller
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: 10.0.8.8:8088/kubeflow/5426bead8ad78671b7825c2d1e216829:2022-10-07
          args:
            - "services.serving.knative.dev"
            - "configurations.serving.knative.dev"
            - "revisions.serving.knative.dev"
            - "routes.serving.knative.dev"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
